services:
  app:
    image: node:lts
    command: sh -c "npm install && npm run build && npm run start"
    container_name: talking-heads
    ports:
      - 3003
    working_dir: /app
    build: .
    volumes:
      - ./:/app
    environment:
      - SOCKET_HOST=${SOCKET_HOST}
    user: $DOCKER_USER

networks:
  default:
    external: true
    name: scoobydoo